
# Configure a default setup of Home Assistant (frontend, api, etc)
homeassistant:
  time_zone: Europe/Berlin
  elevation: 52
default_config:

#logger:
#  default: notset
#testing
# Text to speech

influxdb:
  host: 192.168.178.55
  include:
    entities:
       - sensor.solar_yield
       - sensor.battery_consumption
       - sensor.grid_consumption
       - sensor.house_consumption
       - sensor.battery_charging
       - sensor.grid_feed_in

binary_sensor:
  - platform: ping
    host: !secret host_modbus_server_ip
    name: Modbus API PiServer
  - platform: ping
    host: !secret host_solar_server_ip
    name: Kostal Server
  - platform: ping
    host: !secret host_heating_server_ip
    name: Heizung Server
  - platform: ping
    host: !secret host_vacuum_ip
    name: Wall-E
  - platform: ping
    host: !secret host_repeater_ip
    name: Echorep
  - platform: ping
    host: !secret host_battery_server_ip
    name: Battery
  - platform: ping
    host: !secret host_blinds_server_ip
    name: Blinds Server

weather:
  - platform: openweathermap
    api_key: !secret owm_api_key

mqtt:
  broker: !secret host_mqtt_broker_ip
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant



input_boolean:
  blinds_east:
    name: Blinds east down
    initial: 'off'
    icon: mdi:wheather-sunny-alert

sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
  themes: !include themes.yaml

tesla:
  username: !secret tesla_username
  password: !secret tesla_password

utility_meter:
  solar_yield_daily:
    source: sensor.integer_solar_yield
    cycle: daily
  home_energy_daily:
    source: sensor.integer_house_energy
    cycle: daily
  power_home_consumption_daily:
    source: sensor.integer_house_consumption
    cycle: daily
  solar_generation_monthly:
    source: sensor.integer_solar_yield
    cycle: monthly
  power_home_energy_monthly:
    source: sensor.integer_house_energy
    cycle: monthly
  power_home_consumption_monthly:
    source: sensor.integer_house_consumption
    cycle: monthly
  solar_generation_yearly:
    source: sensor.integer_solar_yield
    cycle: yearly
  power_home_energy_yearly:
    source: sensor.integer_house_energy
    cycle: daily
  power_home_consumption_yearly:
    source: sensor.integer_house_consumption
    cycle: daily


  power_heliotherm_daily:
    source: sensor.stromz_leistung
    cycle: daily
  power_water_daily:
    source: sensor.stromz_brauchwasser
    cycle: daily
  power_heating_daily:
    source: sensor.stromz_heizung
    cycle: daily
  power_water_heating_daily:
    source: sensor.stromz_gesamt
    cycle: daily
  power_heliotherm_monthly:
    source: sensor.stromz_leistung
    cycle: monthly
  power_water_monthly:
    source: sensor.stromz_brauchwasser
    cycle: monthly
  power_heating_monthly:
    source: sensor.stromz_heizung
    cycle: monthly
  power_water_heating_monthly:
    source: sensor.stromz_gesamt
    cycle: monthly
  power_heliotherm_yearly:
    source: sensor.stromz_leistung
    cycle: yearly
  power_water_yearly:
    source: sensor.stromz_brauchwasser
    cycle: yearly
  power_heating_yearly:
    source: sensor.stromz_heizung
    cycle: daily
  power_water_heating_yearly:
    source: sensor.stromz_gesamt
    cycle: daily
  
duckdns:
  domain: !secret duckdnsdomain
  access_token: !secret duckdnstoken

ios:
  push:
    categories:
      - name: Power for marvin
        identifier: 'marvinpower'
        actions:
          - identifier: 'POWER_MARVIN'
            title: 'Power up Marvin'
            activationMode: 'background'
            authenticationRequired: true
            destructive: true
            behavior: 'default'
          - identifier: 'NO_POWER_MARVIN'
            title: 'No power for marvin'
            activationMode: 'background'
            authenticationRequired: true
            destructive: false
            behavior: 'textInput'
            textInputButtonTitle: 'Silencio!'
            textInputPlaceholder: 'Placeholder'