  sensor.esp8266_3_temperature:
    friendly_name: "Temp bedroom"

  sensor.esp8266_3_humidity:
   friendly_name: "Hum bedroom"

  sensor.esp8266_2_humidity:
   friendly_name: "Hum living room"

  sensor.esp8266_2_temperature:
   friendly_name: "Temp living room"