SteelBlueColors:
  text-color: "white"
  text-medium-light-color: "orange"
  text-medium-color: "olivedrab"
  text-dark-color: "olivedrab"
  accent-color: "crimson"
  accent-medium-color: "crimson"
  background-color: "#484E59"
  background-color-2: "#484E59"
  background-card-color: "#4f5663"
  card-background-color: "#484E59"
  border-color: "red"
  primary-color: "steelblue"
  text-primary-color: "white"
  paper-listbox-background-color: "#4f5663"
  sidebar-icon-color: "steelblue"
  sidebar-selected-icon-color: "lightsteelblue"
  sidebar-selected-text-color: "lightsteelblue"
  sidebar-background-color: "#484E59"
  paper-card-header-color: "red"
  primary-background-color: "#484E59"
  mdc-theme-primary: "var(--accent-medium-color)"
  paper-card-background-color: "var(--background-card-color)"
  dark-primary-color: "var(--text-color)"
  primary-text-color: "#e1e1e3"
  paper-listbox-color: "yellow"
  light-primary-color: "steelblue"
  secondary-text-color: "olivedrab"
  disabled-text-color: "BlueViolet "
  paper-dialog-button-color: "yellow"
  secondary-background-color: "#484E59"
  paper-item-icon-color: "steelblue"
  paper-item-icon-active-color: "darkorange"
  paper-toggle-button-checked-button-color: "olivedrab"
  paper-toggle-button-checked-bar-color: "darkgray"
  paper-toggle-button-unchecked-button-color: "IndianRed  "
  paper-toggle-button-unchecked-bar-color: "#767682"
  shadow-elevation-2dp_-_box-shadow: "inset 0px 0px 0px 1px var(--border-color)"
  shadow-elevation-4dp_-_box-shadow: "var(--shadow-elevation-2dp_-_box-shadow)"
  shadow-elevation-6dp_-_box-shadow: "var(--shadow-elevation-2dp_-_box-shadow)"
  shadow-elevation-8dp_-_box-shadow: "var(--shadow-elevation-2dp_-_box-shadow)"
  shadow-elevation-10dp_-_box-shadow: "var(--shadow-elevation-2dp_-_box-shadow)"
  shadow-elevation-12dp_-_box-shadow: "var(--shadow-elevation-2dp_-_box-shadow)"
  shadow-elevation-14dp_-_box-shadow: "var(--shadow-elevation-2dp_-_box-shadow)"
  shadow-elevation-16dp_-_box-shadow: "0px 0px 0px 3px var(--text-dark-color)"
Light - Navy Blue:
  ### Main Interface Colors ###
  primary-color: "#395274"
  light-primary-color: "#5F81B0"
  primary-background-color: "#F6F7F9"
  secondary-background-color: var(--primary-background-color)
  divider-color: "#D6DFEB"
  ### Text ###
  primary-text-color: "#395274"
  secondary-text-color: "#B24444"
  text-primary-color: "#FFFFFF"
  disabled-text-color: "#88A1C4"
  ### Sidebar Menu ###
  sidebar-icon-color: "#395274"
  sidebar-text-color: var(--sidebar-icon-color)
  sidebar-selected-background-color: var(--primary-background-color)
  sidebar-selected-icon-color: "#B24444"
  sidebar-selected-text-color: var(--sidebar-selected-icon-color)
  ### States and Badges ###
  state-icon-color: "#B24444"
  state-icon-active-color: "#FBCD41"
  state-icon-unavailable-color: var(--disabled-text-color)
  ### Sliders ###
  paper-slider-knob-color: "#B24444"
  paper-slider-knob-start-color: var(--paper-slider-knob-color)
  paper-slider-pin-color: var(--paper-slider-knob-color)
  paper-slider-active-color: var(--paper-slider-knob-color)
  paper-slider-secondary-color: var(--light-primary-color)
  ### Labels ###
  label-badge-background-color: "#FFFFFF"
  label-badge-text-color: "#395274"
  label-badge-red: "#B24444"
  ### Cards ###
  paper-card-background-color: "#FFFFFF"
  paper-listbox-background-color: var(--primary-background-color)
  ### Toggles ###
  paper-toggle-button-checked-button-color: "#B24444"
  paper-toggle-button-checked-bar-color: "#FFA3A3"
  paper-toggle-button-unchecked-button-color: "#B24444"
  paper-toggle-button-unchecked-bar-color: "#9CB2CE"
  ### Table row ###
  table-row-background-color: var(--primary-background-color)
  table-row-alternative-background-color: var(--secondary-background-color)

############ Summer Breeze Theme ##########################################################################################  
summer_breeze:
  lovelace-background: 'center / cover no-repeat url("/local/background-summer_breeze.jpg") fixed' #Background-image
  # Define basic colors
  element-dark-color: "rgba(44,29,5,0.9)"                                                                   # nearly black
  element-light-color: "rgb(47, 35, 23,0.6)"                                                                # Medium grey
  element-medium-color: "rgba(44,29,5,0.7)"                                                                 # Light grey
  accent-color: 'rgba(218,165,32,0.8)'                                                                      # dark-yellow
  accent-color-darker: 'rgba(184,134,11,1)' 
  background-color: '#F7F8F9'                                                                               # Light grey 
  background-color-2: '#dedfe0'                                                                             # Light grey 
  transparent-background-color: 'rgba(255,255,255,0.2)'                                                     # white transparent
  #transparent-background-color-darker: 'rgba(89,87,86,0.15)'                                               # grey transparent
  less-transparent-background-color: 'rgba(89,87,86,0.5)'                                                   # grey less transparent
  non-transparent-background-color: '#A28E66'                                                               # non transparent yelowish grey
  border-color: '#EAEAEA'                                                                                   # Light grey border
  
  # Header
  primary-color: 'var(--non-transparent-background-color)'                                                  # color of the headers background, the highlighted element in the Sidebar, buttons in lovelace
  text-primary-color: 'var(--element-medium-color)'
  # Compact Custom Header
  cch-background: 'var(--less-transparent-background-color)'
  cch-button-color-menu: 'var(--element-dark-color)'

  # Left Menu
  paper-listbox-background-color: transparent #'var(--non-transparent-background-color)'                    # Background of the Menu in sidebar (containing shortcuts)

  # UI
  #paper-card-header-color: #'var(--element-dark-color)'                                                    # Title in settings - doesnt seem to have any effect
  primary-background: 'var(--background-color)'                                                             # background of dialogs, title background in left menu)
  sidebar-background: 'var(--background-color-2)'
  app-toolbar-background-color: transparent

  # Card
  paper-card-background-color: 'var(--transparent-background-color)'                                        # Background of cards -> mostly transparent
  ha-card-border-radius: '10px'                                                                             # rounded corners
  #dark-primary-color: red #'var(--element-dark-color)'                                                     # doesnt seem to have any effect
  #primary-element-dark-color: red #'var(--element-dark-color)'                                             # doesnt seem to have any effect
  paper-listbox-color: 'var(--element-dark-color)'
  light-primary-color: 'var(--accent-color)'
  secondary-element-dark-color: green #'var(--element-light-color)'
  paper-dialog-button-color: red #'var(--element-dark-color)'
  secondary-background-color: transparent #'var(--less-transparent-background-color)'                       # secondary color that can be used by cards, e.g. custom updater card uses it to color every second row, also header of popups

  paper-dialog-background-color: 'var(--background-color)'                                                  # background color of dialogs that appear when clicking on a entity
  paper-dialog-color: 'var(--element-light-color)'                                                          # text color of these dialogs
  paper-dialog-header-background: 'var(--element-dark-color)'
  more-info-header-color: 'var(--element-dark-color)'
  more-info-header-background: white #'var(--less-transparent-background-color)'

  
  # Icons
  paper-item-icon-color: 'var(--element-light-color)'                                                       # Off
  paper-item-icon-active-color: 'var(--accent-color-darker)'                                                # On (gets overriden by light color if its sent)
  
  # Switches
  paper-toggle-button-checked-button-color: '#FFF'                                                          # Knob On
  paper-toggle-button-checked-bar-color:  'var(--accent-color-darker)'                                      # Background On
  paper-toggle-button-unchecked-button-color: '#FFF'                                                        # Knob Off
  paper-toggle-button-unchecked-bar-color: 'var(--element-light-color)'                                     # Background Off
                                                                              
  
  #slider
  paper-slider-knob-color: 'white'                                                                          # color of the handle
  paper-slider-container-color: 'rgba(44,29,5,0.2)'                                                         # color of the sliders line
  paper-slider-active-color: 'rgba(44,29,5,0.4)'                                                            # color of the active part of the slider (left of the knob)
  paper-slider-knob-start-color: 'rgba(255,255,255,0.6)'                                                    # color of the knob when beeing at 0
  paper-slider-height: '5px'                                                                                # thickness of the sliders' line

  #Progress
  paper-progress-height: 7px                                                                                # height of the progress bars

  # Shadows
  shadow-elevation-2dp_-_box-shadow: 'inset 0px 0px 0px 1px var(--border-color)'
  shadow-elevation-4dp_-_box-shadow: 'var(--shadow-elevation-2dp_-_box-shadow)'
  shadow-elevation-6dp_-_box-shadow: 'var(--shadow-elevation-2dp_-_box-shadow)'
  shadow-elevation-8dp_-_box-shadow: 'var(--shadow-elevation-2dp_-_box-shadow)'
  shadow-elevation-10dp_-_box-shadow: 'var(--shadow-elevation-2dp_-_box-shadow)'
  shadow-elevation-12dp_-_box-shadow: 'var(--shadow-elevation-2dp_-_box-shadow)'
  shadow-elevation-14dp_-_box-shadow: 'var(--shadow-elevation-2dp_-_box-shadow)'
  shadow-elevation-16dp_-_box-shadow: '0px 0px 0px 3px var(--light-color)'
  ha-card-box-shadow: "0px 5px 5px rgba(0,0,0,0.3)"


############# Aqua Fiesta Theme ##################################################################################################
aqua_fiesta:
  accent-color: "#f9a825"
  card-background-color: var(--secondary-background-color)
  dark-primary-color: "#007c91"
  default-primary-color: var(--primary-color)
  disabled-text-color: '#777777'
  ha-user-badge: var(--accent-color)
  label-badge-red: var(--primary-color)
  label-badge-text-color: var(--primary-text-color)
  light-primary-color: "#5ddef4"
  lumo-body-text-color: var(--dark-primary-color)
  lumo-primary-color: var(--text-primary-color)
  lumo-primary-text-color: var(--text-primary-color)
  lumo-secondary-text-color: var(--text-primary-color)
  mdc-theme-primary: var(--primary-color)
  paper-card-background-color: var(--secondary-background-color)
  paper-card-header-color: var(--text-primary-color)
  paper-grey-200: var(--paper-listbox-background-color)
  paper-grey-50: var(--primary-text-color)
  paper-icon-item: var(--accent-color)
  paper-item-icon-active-color: var(--accent-color)
  paper-item-icon-color: var(--primary-text-color)
  paper-item-selected_-_background-color: var(--paper-card-background-color)
  paper-light-blue-500: var(--light-primary-color)
  paper-listbox-background-color: '#2f3030'
  paper-slider-active-color: var(--primary-color)
  paper-slider-container-color: 'linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat'
  paper-slider-knob-color: var(--primary-color)
  paper-slider-knob-start-color: var(--primary-color)
  paper-slider-pin-color: var(--primary-color)
  paper-slider-secondary-color: var(--secondary-background-color)
  paper-tabs-selection-bar-color: var(--primary-color)
  paper-toggle-button-checked-bar-color: var(--primary-color)
  paper-toggle-button-checked-button-color: var(--primary-color)
  paper-toggle-button-checked-ink-color: var(--primary-color)
  primary-background-color: "#636363"
  primary-color: "#00acc1"
  primary-text-color: var(--text-primary-color)
  secondary-background-color: "#494949"
  secondary-text-color: var(--primary-color)
  sidebar-icon-color: var(--disabled-text-color)
  table-row-alternative-background-color: var(--paper-card-background-color)
  table-row-background-color: var(--paper-card-background-color)
  text-primary-color: "#dae0e0"