SteelBlueColors:
  text-color: "white"
  text-medium-light-color: "orange"
  text-medium-color: "olivedrab"
  text-dark-color: "olivedrab"
  accent-color: "crimson"
  accent-medium-color: "crimson"
  background-color: "#484E59"
  background-color-2: "#484E59"
  background-card-color: "#4f5663"
  card-background-color: "#484E59"
  border-color: "red"
  primary-color: "steelblue"
  text-primary-color: "white"
  paper-listbox-background-color: "#4f5663"
  sidebar-icon-color: "steelblue"
  sidebar-selected-icon-color: "lightsteelblue"
  sidebar-selected-text-color: "lightsteelblue"
  sidebar-background-color: "#484E59"
  paper-card-header-color: "red"
  primary-background-color: "#484E59"
  mdc-theme-primary: "var(--accent-medium-color)"
  paper-card-background-color: "var(--background-card-color)"
  dark-primary-color: "var(--text-color)"
  primary-text-color: "#e1e1e3"
  paper-listbox-color: "yellow"
  light-primary-color: "steelblue"
  secondary-text-color: "olivedrab"
  disabled-text-color: "BlueViolet "
  paper-dialog-button-color: "yellow"
  secondary-background-color: "#484E59"
  paper-item-icon-color: "steelblue"
  paper-item-icon-active-color: "darkorange"
  paper-toggle-button-checked-button-color: "olivedrab"
  paper-toggle-button-checked-bar-color: "darkgray"
  paper-toggle-button-unchecked-button-color: "IndianRed  "
  paper-toggle-button-unchecked-bar-color: "#767682"
  shadow-elevation-2dp_-_box-shadow: "inset 0px 0px 0px 1px var(--border-color)"
  shadow-elevation-4dp_-_box-shadow: "var(--shadow-elevation-2dp_-_box-shadow)"
  shadow-elevation-6dp_-_box-shadow: "var(--shadow-elevation-2dp_-_box-shadow)"
  shadow-elevation-8dp_-_box-shadow: "var(--shadow-elevation-2dp_-_box-shadow)"
  shadow-elevation-10dp_-_box-shadow: "var(--shadow-elevation-2dp_-_box-shadow)"
  shadow-elevation-12dp_-_box-shadow: "var(--shadow-elevation-2dp_-_box-shadow)"
  shadow-elevation-14dp_-_box-shadow: "var(--shadow-elevation-2dp_-_box-shadow)"
  shadow-elevation-16dp_-_box-shadow: "0px 0px 0px 3px var(--text-dark-color)"
Light - Navy Blue:
  ### Main Interface Colors ###
  primary-color: "#395274"
  light-primary-color: "#5F81B0"
  primary-background-color: "#F6F7F9"
  secondary-background-color: var(--primary-background-color)
  divider-color: "#D6DFEB"
  ### Text ###
  primary-text-color: "#395274"
  secondary-text-color: "#B24444"
  text-primary-color: "#FFFFFF"
  disabled-text-color: "#88A1C4"
  ### Sidebar Menu ###
  sidebar-icon-color: "#395274"
  sidebar-text-color: var(--sidebar-icon-color)
  sidebar-selected-background-color: var(--primary-background-color)
  sidebar-selected-icon-color: "#B24444"
  sidebar-selected-text-color: var(--sidebar-selected-icon-color)
  ### States and Badges ###
  state-icon-color: "#B24444"
  state-icon-active-color: "#FBCD41"
  state-icon-unavailable-color: var(--disabled-text-color)
  ### Sliders ###
  paper-slider-knob-color: "#B24444"
  paper-slider-knob-start-color: var(--paper-slider-knob-color)
  paper-slider-pin-color: var(--paper-slider-knob-color)
  paper-slider-active-color: var(--paper-slider-knob-color)
  paper-slider-secondary-color: var(--light-primary-color)
  ### Labels ###
  label-badge-background-color: "#FFFFFF"
  label-badge-text-color: "#395274"
  label-badge-red: "#B24444"
  ### Cards ###
  paper-card-background-color: "#FFFFFF"
  paper-listbox-background-color: var(--primary-background-color)
  ### Toggles ###
  paper-toggle-button-checked-button-color: "#B24444"
  paper-toggle-button-checked-bar-color: "#FFA3A3"
  paper-toggle-button-unchecked-button-color: "#B24444"
  paper-toggle-button-unchecked-bar-color: "#9CB2CE"
  ### Table row ###
  table-row-background-color: var(--primary-background-color)
  table-row-alternative-background-color: var(--secondary-background-color)
